# Generated by Django 2.2.16 on 2021-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(default=0),
        ),
    ]
