# Generated by Django 2.2.16 on 2021-09-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20210911_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='titles', to='reviews.Category'),
        ),
    ]
