# Generated by Django 2.2.16 on 2021-09-11 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20210911_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='title',
            old_name='text',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='title',
            name='Category',
        ),
        migrations.AddField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='reviews.Category'),
        ),
        migrations.AddField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
